# Generated by Django 4.1.7 on 2023-03-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='vote',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.IntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')], default=1),
        ),
    ]
