# Generated by Django 4.1.7 on 2023-03-21 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_remove_vote_vote_vote_vote_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
